# Generated by Django 3.2.25 on 2024-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_serial_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
