# Generated by Django 3.2.25 on 2024-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_payment_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_reference_no',
        ),
        migrations.AddField(
            model_name='payment',
            name='json_ext',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
